"""Catalog of sacred runs, grouped by the settings each run was launched with.

Each run's run.json records the exact sacred overrides it was launched with
(meta.config_updates). Runs with the same alg, env and overrides (seed aside)
form a group, given a readable label built from the run's resolved config.
The catalog is written to run_catalog.yaml next to this file, so a run can be
found by grepping it, and looked up here:

    import run_catalog as rc        # with scripts/ on sys.path, like load_results
    rc.find("SelfishSpread", "potential", "c1-6-6")   # matching groups
    rc.runs("<label or id>")        # [alg, env, seed, run, path], as load_results
    rc.load_group("<label or id>", ["test_return_mean"])   # curves, as load_results.load_runs

Labels are generated; to rename a group or note what it was for, add its id to
run_catalog_notes.yaml and rebuild:

    python scripts/run_catalog.py build
    python scripts/run_catalog.py find potential c1-6-6
    python scripts/run_catalog.py show <label or id>
"""
import argparse
import hashlib
import json
import re
from collections import defaultdict
from pathlib import Path

import pandas as pd
import yaml

import load_results

HERE = Path(__file__).resolve().parent
CATALOG = HERE / "run_catalog.yaml"
NOTES = HERE / "run_catalog_notes.yaml"
SACRED = load_results.SACRED

# A run this short is a smoke test, not a result.
SMOKE_T_MAX = 5_000

RULES = {
    "joint_overspend": "overspend",
    "joint_overspend_increment": "ovs-inc",
    "joint_budget_increment": "budget-inc",
    "joint_budget_signed_increment": "signed",
    "joint_overspend_potential": "potential",
}
CONCESSIONS = {
    "utopian_table": "exact",
    "optimq": "oq",
    "optimq_additive_linear": "oq-add",
    "optimq_additive_mlp": "oq-mlp",
}

HEADER = """\
# Generated by scripts/run_catalog.py from epymarl/results/sacred; do not edit.
# Rename a group or add a note in run_catalog_notes.yaml (keyed by id), then
# rebuild with `python scripts/run_catalog.py build`.
#
# One entry per group of COMPLETED runs launched with the same alg, env and
# sacred overrides (seed aside). Run directories are
#   epymarl/results/sacred/<alg>/<env>/<run>
#
#   label     <env>/<alg>/<descriptor>. For budget runs the descriptor is: rule
#             (overspend = joint_overspend, ovs-inc = joint_overspend_increment,
#             budget-inc, signed = joint_budget_signed_increment, potential),
#             initial budget (c1-6-6), concession (exact = utopian_table,
#             oq = optimq, oq-add = optimq_additive_linear,
#             oq-mlp = optimq_additive_mlp), critic fixes
#             (stable = huber + layer_norm, -noclip without reward_range,
#             slow = target_tau 0.005 with mse), data (warmup = random-play
#             warmup, xonly = critic trained on exploration only, x<a>-<b> =
#             exploration rate/probability from a to b, /i<n> = every n
#             rollouts), then t_max. Settings that still tell groups apart are
#             appended as key=value. "smoke/" marks runs of <= 5k steps.
#   era       code that produced the runs: no-budget; budget-v1-wrapper (env
#             wrapper, critic updates_per_run); budget-v2-exploration (wrapper
#             plus budget.exploration rollouts); budget-v3-runner (budget
#             runners with concession data/training, the current code)
#   commit    git HEAD at launch; "dirty" means uncommitted code also ran
#   settings  the overrides the runs were launched with (seed removed)
#   sweep     for runs launched by scripts/sweeps: the sweep, its axis options
#             and any --set overrides (look them up with
#             `python scripts/sweeps status <sweep> --list`)
#   incomplete  runs with these settings that did not complete: {run: status}
"""


# --- reading sacred -------------------------------------------------------

def _flatten(d, prefix=""):
    out = {}
    for k, v in d.items():
        if isinstance(v, dict) and v:
            out.update(_flatten(v, f"{prefix}{k}."))
        else:
            out[prefix + k] = v
    return out


def _read_runs(sacred=SACRED):
    """Yield one dict per sacred run dir that has its metadata."""
    for path in sorted(Path(sacred).glob("*/*/*")):
        if not path.name.isdigit():
            continue
        try:
            info = json.loads((path / "run.json").read_text())
            config = json.loads((path / "config.json").read_text())
        except (OSError, json.JSONDecodeError):
            continue
        settings = _flatten(info.get("meta", {}).get("config_updates", {}))
        settings.pop("seed", None)
        # Runs launched by scripts/sweeps carry their sweep tag in --comment.
        try:
            tag = json.loads(info.get("meta", {}).get("options", {}).get("--comment") or "null")
        except json.JSONDecodeError:
            tag = None
        repo = (info.get("experiment", {}).get("repositories") or [{}])[0]
        yield {
            "alg": path.parent.parent.name,
            "env": path.parent.name,
            "run": int(path.name),
            "seed": config.get("seed"),
            "status": info.get("status"),
            "start": (info.get("start_time") or "")[:10],
            "commit": (repo.get("commit") or "?")[:7] + (" dirty" if repo.get("dirty") else ""),
            "settings": settings,
            "config": config,
            "tag": tag if isinstance(tag, dict) and "sweep" in tag else None,
        }


# --- describing a group -------------------------------------------------

def _num(x):
    return f"{x:g}" if isinstance(x, (int, float)) and not isinstance(x, bool) else str(x)


def _steps(n):
    if n >= 1_000_000:
        return f"{n / 1_000_000:g}M"
    if n >= 1_000:
        return f"{n / 1_000:g}k"
    return str(n)


def _value(v):
    if isinstance(v, (list, tuple)):
        return "-".join(_num(x) for x in v)
    if v is None:
        return "none"
    if isinstance(v, bool):
        return str(v).lower()
    return _num(v)


def era(config):
    budget = config.get("budget")
    if not budget or not budget.get("enabled"):
        return "no-budget"
    if "exploration" in budget:
        return "budget-v2-exploration"
    if any(isinstance(a, dict) and "data" in a
           for a in budget.get("concession_args", {}).values()):
        return "budget-v3-runner"
    return "budget-v1-wrapper"


def _critic_tokens(args):
    if args.get("loss") == "huber" and args.get("layer_norm"):
        return ["stable" + ("-noclip" if args.get("reward_range") is None else "")]
    if args.get("target_tau") == 0.005 and args.get("loss", "mse") == "mse":
        return ["slow"]
    return []


def _exploration_tokens(budget, args):
    """Exploration/data tokens for the v2 (budget.exploration) and v3 (data) code."""
    tokens = []
    exploration = budget.get("exploration")
    if exploration is not None:
        if exploration.get("policy") is None:
            return []
        if exploration.get("warmup_steps") or exploration.get("warmup_rollouts"):
            tokens.append("warmup")
        if exploration.get("exploration_only"):
            tokens.append("xonly")
        start, finish = exploration.get("prob_start", 0), exploration.get("prob_finish", 0)
        if start or finish:
            x = f"x{_num(start)}-{_num(finish)}"
            if exploration.get("interval", 1) > 1:
                x += f"/i{exploration['interval']}"
            tokens.append(x)
        return tokens
    data = args.get("data")
    if not data or data.get("explore_policy") is None:
        return []
    if data.get("warmup_steps"):
        tokens.append("warmup")
    if data.get("policy_fraction") == 0:
        tokens.append("xonly")
    schedule = data.get("explore")
    sched_args = data.get("explore_args", {}).get(schedule, {})
    if schedule == "constant" and sched_args.get("rate"):
        tokens.append(f"x{_num(sched_args['rate'])}")
    elif schedule == "anneal":
        tokens.append(f"x{_num(sched_args.get('start'))}-{_num(sched_args.get('finish'))}")
    return tokens


def summary(config):
    """The settings that matter most, from the resolved config."""
    out = {"t_max": config.get("t_max")}
    budget = config.get("budget")
    if budget and budget.get("enabled"):
        out.update(rule=budget.get("rule"), initial_budget=budget.get("initial_budget"),
                   observe_budget=budget.get("observe_budget"),
                   concession=budget.get("concession"))
    return out


def descriptor(config):
    tokens = []
    budget = config.get("budget")
    if budget and budget.get("enabled"):
        tokens.append(RULES.get(budget.get("rule"), str(budget.get("rule"))))
        tokens.append("c" + _value(budget.get("initial_budget")))
        concession = budget.get("concession")
        tokens.append(CONCESSIONS.get(concession, str(concession)))
        args = budget.get("concession_args", {}).get(concession) or {}
        if concession != "utopian_table":
            tokens += _critic_tokens(args)
            tokens += _exploration_tokens(budget, args)
    tokens.append(_steps(config.get("t_max", 0)))
    return "-".join(tokens)


def _short_env(env):
    """Env id without its package and version: mpe_envs:SelfishSpread-3ag-v0 -> SelfishSpread-3ag."""
    return re.sub(r"-v\d+$", "", env.split(":", 1)[-1])


def _distinguish(groups):
    """key=value suffixes telling apart groups whose labels collide."""
    keys = sorted({k for g in groups for k in g["settings"]})
    differing = [k for k in keys
                 if len({json.dumps(g["settings"].get(k), sort_keys=True) for g in groups}) > 1]

    def short(key):
        # Shortest dotted suffix no other differing key shares.
        parts = key.split(".")
        for n in range(1, len(parts) + 1):
            suffix = ".".join(parts[-n:])
            if sum(k.endswith(suffix) for k in differing) == 1:
                return suffix
        return key

    for g in groups:
        g["label"] += "/" + ",".join(
            f"{short(k)}={_value(g['settings'].get(k, '<unset>'))}" for k in differing
        )


# --- building --------------------------------------------------------------

def _group_id(alg, env, settings):
    key = json.dumps([alg, env, settings], sort_keys=True, default=str)
    return hashlib.sha1(key.encode()).hexdigest()[:8]


def _load_notes():
    if not NOTES.exists():
        return {}
    return yaml.safe_load(NOTES.read_text()) or {}


def build(sacred=SACRED):
    """Group every sacred run; returns the catalog as a list of dicts."""
    by_key = defaultdict(list)
    for run in _read_runs(sacred):
        by_key[(run["alg"], run["env"], json.dumps(run["settings"], sort_keys=True, default=str))].append(run)

    notes = _load_notes()
    groups = []
    for (alg, env, _), runs in by_key.items():
        done = sorted((r for r in runs if r["status"] == "COMPLETED"), key=lambda r: r["run"])
        if not done:
            continue
        config = done[-1]["config"]
        gid = _group_id(alg, env, done[0]["settings"])
        smoke = (config.get("t_max") or 0) <= SMOKE_T_MAX
        label = f"{'smoke/' if smoke else ''}{_short_env(env)}/{alg}/{descriptor(config)}"
        commits = sorted({r["commit"] for r in done})
        dates = sorted(r["start"] for r in done if r["start"])
        group = {
            "label": label,
            "id": gid,
            "alg": alg,
            "env": env,
            "era": era(config),
            "smoke": smoke,
            "seeds": sorted({r["seed"] for r in done}),
            "runs": [r["run"] for r in done],
            "dates": f"{dates[0]} .. {dates[-1]}" if dates else None,
            "commit": commits[0] if len(commits) == 1 else commits,
            "summary": summary(config),
            "settings": done[0]["settings"],
        }
        tag = done[0]["tag"]
        if tag:
            group["sweep"] = {"name": tag["sweep"], "axes": tag.get("axes")}
            if tag.get("set"):
                group["sweep"]["set"] = tag["set"]
        incomplete = {r["run"]: r["status"] for r in runs if r["status"] != "COMPLETED"}
        if incomplete:
            group["incomplete"] = dict(sorted(incomplete.items()))
        note = notes.get(gid) or {}
        if note.get("note"):
            group["note"] = note["note"]
        group["_custom_label"] = note.get("label")
        groups.append(group)

    # Generated labels that collide get the settings that tell them apart.
    by_label = defaultdict(list)
    for g in groups:
        if not g["_custom_label"]:
            by_label[g["label"]].append(g)
    for same in by_label.values():
        if len(same) > 1:
            _distinguish(same)
    for g in groups:
        if g.pop("_custom_label") is not None:
            g["label"] = notes[g["id"]]["label"]

    seen = defaultdict(list)
    for g in groups:
        seen[g["label"]].append(g["id"])
    dupes = {label: ids for label, ids in seen.items() if len(ids) > 1}
    if dupes:
        raise ValueError(f"labels used by more than one group: {dupes}")
    return sorted(groups, key=lambda g: (g["env"], g["alg"], g["label"]))


def write(groups, path=CATALOG):
    body = yaml.safe_dump(groups, sort_keys=False, default_flow_style=None, width=100)
    path.write_text(HEADER + "\n" + body)


# --- querying --------------------------------------------------------------

def load(path=CATALOG):
    """The catalog as a list of dicts (run `build` first if it is missing)."""
    return yaml.safe_load(path.read_text())


def find(*terms, include_smoke=False, catalog=None):
    """Groups whose label, id, alg or env contain every term (case-insensitive)."""
    terms = [t.lower() for t in terms]
    out = []
    for g in catalog or load():
        if g["smoke"] and not include_smoke:
            continue
        text = " ".join([g["label"], g["id"], g["alg"], g["env"]]).lower()
        if all(t in text for t in terms):
            out.append(g)
    return out


def get(label_or_id, catalog=None):
    """One group, by exact label or id."""
    for g in catalog or load():
        if label_or_id in (g["label"], g["id"]):
            return g
    raise KeyError(f"no catalog group with label or id {label_or_id!r}")


def runs(label_or_id, catalog=None):
    """[alg, env, seed, run, path] for a group's completed runs, as load_results.find_runs."""
    g = get(label_or_id, catalog)
    rows = []
    for run in g["runs"]:
        path = SACRED / g["alg"] / g["env"] / str(run)
        config = json.loads((path / "config.json").read_text())
        rows.append({"alg": g["alg"], "env": g["env"], "seed": config.get("seed"),
                     "run": run, "path": path})
    return pd.DataFrame(rows)


def load_group(label_or_id, keys, catalog=None, skip_missing=False, dropna=False):
    """Training curves of a group's runs, in load_results.load_runs' long format,
    with a `group` column holding the label."""
    g = get(label_or_id, catalog)
    frames = []
    for row in runs(g["id"], catalog).to_dict("records"):
        path = row.pop("path")
        frame = load_results._metrics_frame(path, keys, dropna=dropna, skip_missing=skip_missing)
        frames.append(frame.assign(**row, group=g["label"]))
    return pd.concat(frames, ignore_index=True)


# --- CLI ---------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("build", help="regenerate run_catalog.yaml from the sacred dirs")
    f = sub.add_parser("find", help="list groups matching every term")
    f.add_argument("terms", nargs="*")
    f.add_argument("--smoke", action="store_true", help="include smoke tests")
    s = sub.add_parser("show", help="print one group")
    s.add_argument("label_or_id")
    args = parser.parse_args()

    if args.cmd == "build":
        groups = build()
        write(groups)
        n_runs = sum(len(g["runs"]) for g in groups)
        print(f"{len(groups)} groups, {n_runs} completed runs -> {CATALOG}")
    elif args.cmd == "find":
        for g in find(*args.terms, include_smoke=args.smoke):
            print(f"{g['id']}  {len(g['runs']):3d} runs  seeds {g['seeds']}  {g['label']}")
    else:
        print(yaml.safe_dump(get(args.label_or_id), sort_keys=False, default_flow_style=None))


if __name__ == "__main__":
    main()
